title: SinricPro

tagline: IOT Cloud Platform

description: >
  Sinric Pro is a IOT Cloud Platform.

twitter_username: sinricpro
github_username:  sinricpro

url: https://help.sinric.pro

defaults:
  -
    values:
      layout: page
      weight: 100   # Used to sort navbar items. Lower weight goes higher on the list.

highlighter: rouge

#environment: production
environment: production

